version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx
    environment:
      DOMAINS: "localhost -> http://nginx:80 #local"
      CLIENT_MAX_BODY_SIZE: 35M
    volumes:
      - ./docker/ssl_certs:/var/lib/https-portal

  nginx:
    image: nginx:latest
    depends_on:
      - laravel
      - mailpit
      - adminer
    working_dir: /var/www/app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/app:cached

  laravel:
    build: ./docker/laravel
    working_dir: /var/www/app
    volumes:
      - ./laravel:/var/www/app:cached
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql:cached

  db-test:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tmpfs:
      - /var/lib/mysql

  node:
    image: node:18
    user: "__UID__:__GID__"
    working_dir: /var/www/app
    volumes:
      - ./laravel:/var/www/app:cached

  mailpit:
    image: axllent/mailpit
    environment:
      MP_WEBROOT: mailpit

  adminer:
    image: adminer

networks:
  shared-network:
    external: true
